services:
  # Backend API service
  - type: web
    name: dashboard-control-back
    env: python
    region: virginia  # Choose your region
    buildCommand: ./build.sh
    startCommand: gunicorn project.wsgi:application --bind 0.0.0.0:$PORT
    envVars:
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DJANGO_DEBUG
        value: False
      - key: IS_RENDER
        value: True
      - key: POSTGRES_DB
        fromDatabase:
          name: dashboard-control-db
          property: database
      - key: POSTGRES_USER
        fromDatabase:
          name: dashboard-control-db
          property: user
      - key: POSTGRES_PASSWORD
        fromDatabase:
          name: dashboard-control-db
          property: password
      - key: POSTGRES_HOST
        fromDatabase:
          name: dashboard-control-db
          property: host
      - key: POSTGRES_PORT
        fromDatabase:
          name: dashboard-control-db
          property: port
      - key: DJANGO_ALLOWED_HOSTS
        value: "dashboard-control-back.onrender.com,dashboard-control-front.onrender.com"
      - key: CORS_ALLOWED_ORIGINS
        value: "https://dashboard-control-front.onrender.com"
      - key: CSRF_TRUSTED_ORIGINS
        value: "https://dashboard-control-front.onrender.com"
      - key: DJANGO_SECURE_SSL_REDIRECT
        value: True
      - key: DJANGO_SESSION_COOKIE_SECURE
        value: True
      - key: DJANGO_CSRF_COOKIE_SECURE
        value: True

  # Frontend service
  - type: web
    name: dashboard-control-front
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: VITE_API_URL
        value: https://dashboard-control-back.onrender.com