# Generated by Django 5.1.7 on 2025-05-02 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TestData',
            fields=[
                ('order_id', models.IntegerField(primary_key=True, serialize=False)),
                ('order_class_id', models.IntegerField()),
                ('order_status_id', models.IntegerField()),
                ('lookup_code', models.CharField(max_length=255)),
                ('fetched_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Test Data',
                'verbose_name_plural': 'Test Data',
                'db_table': 'data_testdata',
            },
        ),
    ]
