# Generated by Django 5.1.7 on 2025-05-15 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='orders',
            unique_together={('order_number', 'shipment_number')},
        ),
    ]
