# Generated by Django 5.1.7 on 2025-05-20 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_alter_orders_unique_together'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orders',
            old_name='order_or_shipment_class_type',
            new_name='order_class',
        ),
        migrations.RenameField(
            model_name='orders',
            old_name='inbound_or_outbound',
            new_name='order_type',
        ),
    ]
