# Generated by Django 5.1.7 on 2025-05-22 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0004_orders_day_orders_destination_state_orders_month_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='month',
            field=models.CharField(blank=True, max_length=9, null=True),
        ),
    ]
