# Generated by Django 5.1.7 on 2025-05-22 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0005_alter_orders_month'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='month_name',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='orders',
            name='month',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
