# Generated by Django 5.1.7 on 2025-04-29 15:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Companies',
            },
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_authorized', models.BooleanField(default=False, help_text='Designates whether the user is authorized to access the application.')),
                ('allowed_tabs_list', models.CharField(blank=True, help_text='Comma-separated list of tabs the user can access (e.g., CEO,CIO,Leaders).', max_length=200)),
                ('allowed_companies', models.ManyToManyField(blank=True, help_text='Companies this user is allowed to view data for.', to='access.company')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='access_profile', to=settings.AUTH_USER_MODEL)),
                ('allowed_warehouses', models.ManyToManyField(blank=True, help_text='Warehouses (Leaders tab) this user is allowed to view data for.', to='access.warehouse')),
            ],
        ),
    ]
