# Generated by Django 5.1.7 on 2025-04-29 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0002_warehouse_company'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_name', models.CharField(help_text='Unique identifier for the tab (e.g., CEO, Leaders). Used internally.', max_length=50, unique=True)),
                ('display_name', models.CharField(help_text='User-friendly name for the tab (e.g., CEO View, Leaders View).', max_length=100)),
            ],
            options={
                'ordering': ['display_name'],
            },
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='allowed_tabs_list',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='allowed_tabs',
            field=models.ManyToManyField(blank=True, help_text='Tabs/Views this user is allowed to access.', to='access.tab'),
        ),
    ]
