# Generated by Django 5.1.7 on 2025-04-30 18:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0003_tab_remove_userprofile_allowed_tabs_list_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': 'User Access Profile', 'verbose_name_plural': 'User Access Profiles'},
        ),
        migrations.AddField(
            model_name='userprofile',
            name='email',
            field=models.EmailField(blank=True, db_index=True, help_text='Email para pre-configurar acceso antes del primer login. Se vuelve redundante una vez que el usuario está vinculado.', max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='allowed_companies',
            field=models.ManyToManyField(blank=True, help_text='Compañías a las que este usuario puede ver datos.', to='access.company'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='allowed_tabs',
            field=models.ManyToManyField(blank=True, help_text='Pestañas/Vistas a las que este usuario puede acceder.', to='access.tab'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='allowed_warehouses',
            field=models.ManyToManyField(blank=True, help_text='Almacenes (pestaña Leaders) a los que este usuario puede ver datos.', to='access.warehouse'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='is_authorized',
            field=models.BooleanField(default=False, help_text='Designa si el usuario está autorizado para acceder a la aplicación.'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='access_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
