# Generated by Django 5.1.7 on 2025-05-02 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0004_alter_userprofile_options_userprofile_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tab',
            name='display_name',
            field=models.CharField(help_text='User-friendly name for the tab (e.g., CEO View, Leaders View, Testing View).', max_length=100),
        ),
        migrations.AlterField(
            model_name='tab',
            name='id_name',
            field=models.CharField(help_text='Unique identifier for the tab (e.g., CEO, Leaders, Testing). Used internally.', max_length=50, unique=True),
        ),
    ]
